- name: Deploy Castopod on VPS
  hosts: all
  remote_user: thenerdshow
  vars:
    dir: "/home/{{ ansible_user }}/castopod"
    container_dir: "/var/www/castopod"
    app_port: "8000"
  roles:
    - git_pull
    - docker_restart
