- name: Create networks
  docker_network:
    name: "{{ item }}"
    state: present
  loop:
    - castopod-db
    - castopod-app

- name: Run App container
  docker_container:
    name: castopod-app
    image: castopod/castopod:latest
    env:
      CP_DATABASE_HOSTNAME: castopod-mariadb
      MYSQL_DATABASE: "{{ MYSQL_DATABASE }}"
      MYSQL_USER: "{{ MYSQL_USER }}"
      MYSQL_PASSWORD: "{{ MYSQL_PASSWORD }}"
      CP_BASEURL: "{{ CP_BASEURL }}"
      CP_ANALYTICS_SALT: "{{ CP_ANALYTICS_SALT }}"
      CP_CACHE_HANDLER: redis
      CP_REDIS_HOST: castopod-redis
      CP_REDIS_PASSWORD: "{{ CP_REDIS_PASSWORD }}"
    volumes:
      - "{{ dir }}/castopod-media:/var/www/castopod/public/media"
    networks:
      - name: castopod-db
      - name: castopod-app
    exposed_ports:
      - "{{ app_port }}"
    published_ports:
      - "{{ app_port }}:{{ app_port }}"
    restart: yes
    recreate: yes

- name: Run MariaDB container
  docker_container:
    name: castopod-mariadb
    image: mariadb:10.5
    env:
      MYSQL_ROOT_PASSWORD: "{{ MYSQL_ROOT_PASSWORD }}"
      MYSQL_DATABASE: "{{ MYSQL_DATABASE }}"
      MYSQL_USER: "{{ MYSQL_USER }}"
      MYSQL_PASSWORD: "{{ MYSQL_PASSWORD }}"
    volumes:
      - "{{ dir }}/castopod-db:/var/lib/mysql"
    networks:
      - name: castopod-db
    restart: yes
    recreate: yes

- name: Run Redis container
  docker_container:
    name: castopod-redis
    image: redis:7.0-alpine
    command: "--requirepass {{ CP_REDIS_PASSWORD }}"
    volumes:
      - "{{ dir }}/castopod-cache:/data"
    networks:
      - name: castopod-app
    restart: yes
    recreate: yes

