- name: Stop Docker containers
  docker_container:
    name: "{{ item }}"
    state: absent
  loop:
    - "castopod-app"
    - "castopod-mariadb"
    - "castopod-redis"

- name: Remove Docker networks
  docker_network:
    name: "{{ item }}"
    state: absent
  loop:
    - "castopod-app"
    - "castopod-db"